name: Matomo sample deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment (e.g., dev, test, prod)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod

permissions:
  id-token: write
  contents: write


env:
  AWS_REGION: ca-central-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out Matomo CDK repo
        uses: actions/checkout@v4
        with:
          repository: bcgov/nr-parks-web-analytics-matomo
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CDK CLI
        run: npm install -g aws-cdk

      - name: Install app dependencies
        run: npm ci        
        working-directory: aws/cdk


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          role-session-name: matomo-deployment
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Bootstrap CDK
        run: cdk bootstrap
        working-directory: aws/cdk
        continue-on-error: true  # In case bootstrap was already run

      - name: Deploy with CDK
        run: cdk deploy --all --require-approval never        
        working-directory: aws/cdk

